### ISSUE TITLE
Vulnerable to race condition?

### ISSUE THREAD

**Issue by dominic-p** [nmorsman/node-systemd-notify#1]
Hi, thanks for sharing this module. I just read [this article](https://www.pluralsight.com/tech-blog/systemd-notify-nodejs) that says this technique may be susceptible to a race condition. Have you experienced anything like that in your usage?

**Comment by jmlemetayer** [comment]
[New link to the article.](https://www.pluralsight.com/tech-blog/using-systemd-notify-with-nodejs/)

**Comment by nmorsman** [comment]
Hey there,

I don't think I have run into this race condition yet, however I have always been using this module with the `pid`-option set to the process pid:

```js
notify({
    ready: true,
    pid: process.pid
});
```

If I'm understanding the article correctly this race condition may occur when the pid-option is omitted and systemd is left having to resolve the pid from the calling process. If the calling process exits before systemd resolves the pid the race condition takes place.

This module was due for some maintenance anyway so I've rewritten most of it and added promise support. In addition it will now by default add the process pid when called using `ready: true` or `status: 'something'` without the `pid`-option to ensure that the race condition doesn't take place:
https://github.com/nmorsman/node-systemd-notify/blob/3829ba46529ac0972f6cb5b1a3b7ca9859b67cdf/notify.js#L18-L25

Will publish with v1.0.0!

**Comment by dominic-p** [comment]
Thanks for the explanation. That's really helpful.
